name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Kshitij-0710
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push
