name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Kshitij-0710
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
